// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddQuickLaunchFavorite(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddQuickLaunchFavorite'](arg1, arg2, arg3);
}

export function AttachSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['AttachSession'](arg1, arg2, arg3);
}

export function CloseTerminal() {
  return window['go']['main']['App']['CloseTerminal']();
}

export function CreateSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3, arg4);
}

export function DeleteLaunchConfig(arg1) {
  return window['go']['main']['App']['DeleteLaunchConfig'](arg1);
}

export function DiscoverProjects() {
  return window['go']['main']['App']['DiscoverProjects']();
}

export function GenerateConfigKey(arg1, arg2) {
  return window['go']['main']['App']['GenerateConfigKey'](arg1, arg2);
}

export function GetDefaultLaunchConfig(arg1) {
  return window['go']['main']['App']['GetDefaultLaunchConfig'](arg1);
}

export function GetDesktopTheme() {
  return window['go']['main']['App']['GetDesktopTheme']();
}

export function GetGitBranch(arg1) {
  return window['go']['main']['App']['GetGitBranch'](arg1);
}

export function GetLaunchConfig(arg1) {
  return window['go']['main']['App']['GetLaunchConfig'](arg1);
}

export function GetLaunchConfigs() {
  return window['go']['main']['App']['GetLaunchConfigs']();
}

export function GetLaunchConfigsForTool(arg1) {
  return window['go']['main']['App']['GetLaunchConfigsForTool'](arg1);
}

export function GetProjectRoots() {
  return window['go']['main']['App']['GetProjectRoots']();
}

export function GetQuickLaunchBarVisibility() {
  return window['go']['main']['App']['GetQuickLaunchBarVisibility']();
}

export function GetQuickLaunchFavorites() {
  return window['go']['main']['App']['GetQuickLaunchFavorites']();
}

export function GetScrollback(arg1) {
  return window['go']['main']['App']['GetScrollback'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsGitWorktree(arg1) {
  return window['go']['main']['App']['IsGitWorktree'](arg1);
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function MarkSessionAccessed(arg1) {
  return window['go']['main']['App']['MarkSessionAccessed'](arg1);
}

export function RecordProjectUsage(arg1) {
  return window['go']['main']['App']['RecordProjectUsage'](arg1);
}

export function RemoveQuickLaunchFavorite(arg1) {
  return window['go']['main']['App']['RemoveQuickLaunchFavorite'](arg1);
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2);
}

export function SaveLaunchConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SaveLaunchConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SessionExists(arg1) {
  return window['go']['main']['App']['SessionExists'](arg1);
}

export function SetDesktopTheme(arg1) {
  return window['go']['main']['App']['SetDesktopTheme'](arg1);
}

export function SetQuickLaunchBarVisibility(arg1) {
  return window['go']['main']['App']['SetQuickLaunchBarVisibility'](arg1);
}

export function StartTerminal(arg1, arg2) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2);
}

export function StartTmuxSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartTmuxSession'](arg1, arg2, arg3);
}

export function UpdateQuickLaunchFavoriteName(arg1, arg2) {
  return window['go']['main']['App']['UpdateQuickLaunchFavoriteName'](arg1, arg2);
}

export function UpdateQuickLaunchShortcut(arg1, arg2) {
  return window['go']['main']['App']['UpdateQuickLaunchShortcut'](arg1, arg2);
}

export function UpdateSessionCustomLabel(arg1, arg2) {
  return window['go']['main']['App']['UpdateSessionCustomLabel'](arg1, arg2);
}

export function ValidateMCPConfigPath(arg1) {
  return window['go']['main']['App']['ValidateMCPConfigPath'](arg1);
}

export function WriteTerminal(arg1) {
  return window['go']['main']['App']['WriteTerminal'](arg1);
}
