// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AttachSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['AttachSession'](arg1, arg2, arg3);
}

export function CloseTerminal() {
  return window['go']['main']['App']['CloseTerminal']();
}

export function GetScrollback(arg1) {
  return window['go']['main']['App']['GetScrollback'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ResizeTerminal(arg1, arg2) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2);
}

export function SessionExists(arg1) {
  return window['go']['main']['App']['SessionExists'](arg1);
}

export function StartTerminal(arg1, arg2) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2);
}

export function WriteTerminal(arg1) {
  return window['go']['main']['App']['WriteTerminal'](arg1);
}
