// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AttachSession(arg1:string,arg2:number,arg3:number):Promise<void>;

export function CloseTerminal():Promise<void>;

export function GetScrollback(arg1:string):Promise<string>;

export function GetVersion():Promise<string>;

export function ListSessions():Promise<Array<main.SessionInfo>>;

export function ResizeTerminal(arg1:number,arg2:number):Promise<void>;

export function SessionExists(arg1:string):Promise<boolean>;

export function StartTerminal(arg1:number,arg2:number):Promise<void>;

export function WriteTerminal(arg1:string):Promise<void>;
