// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddQuickLaunchFavorite(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddQuickLaunchFavorite'](arg1, arg2, arg3);
}

export function AddSSHHost(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['AddSSHHost'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function AddScanPath(arg1) {
  return window['go']['main']['App']['AddScanPath'](arg1);
}

export function AttachSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AttachSession'](arg1, arg2, arg3, arg4);
}

export function BrowseLocalDirectory(arg1) {
  return window['go']['main']['App']['BrowseLocalDirectory'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateRemoteSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateRemoteSession'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateSession'](arg1, arg2, arg3, arg4);
}

export function DeleteLaunchConfig(arg1) {
  return window['go']['main']['App']['DeleteLaunchConfig'](arg1);
}

export function DeleteSavedLayout(arg1) {
  return window['go']['main']['App']['DeleteSavedLayout'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DiscoverProjects() {
  return window['go']['main']['App']['DiscoverProjects']();
}

export function GenerateConfigKey(arg1, arg2) {
  return window['go']['main']['App']['GenerateConfigKey'](arg1, arg2);
}

export function GetAutoCopyOnSelectEnabled() {
  return window['go']['main']['App']['GetAutoCopyOnSelectEnabled']();
}

export function GetClickToCursorEnabled() {
  return window['go']['main']['App']['GetClickToCursorEnabled']();
}

export function GetDefaultLaunchConfig(arg1) {
  return window['go']['main']['App']['GetDefaultLaunchConfig'](arg1);
}

export function GetDesktopTheme() {
  return window['go']['main']['App']['GetDesktopTheme']();
}

export function GetExpandedGroups() {
  return window['go']['main']['App']['GetExpandedGroups']();
}

export function GetFileBasedActivityDetection() {
  return window['go']['main']['App']['GetFileBasedActivityDetection']();
}

export function GetFontSize() {
  return window['go']['main']['App']['GetFontSize']();
}

export function GetGitBranch(arg1) {
  return window['go']['main']['App']['GetGitBranch'](arg1);
}

export function GetLaunchConfig(arg1) {
  return window['go']['main']['App']['GetLaunchConfig'](arg1);
}

export function GetLaunchConfigs() {
  return window['go']['main']['App']['GetLaunchConfigs']();
}

export function GetLaunchConfigsForTool(arg1) {
  return window['go']['main']['App']['GetLaunchConfigsForTool'](arg1);
}

export function GetOpenTabState() {
  return window['go']['main']['App']['GetOpenTabState']();
}

export function GetPipelineStats(arg1) {
  return window['go']['main']['App']['GetPipelineStats'](arg1);
}

export function GetProjectRoots() {
  return window['go']['main']['App']['GetProjectRoots']();
}

export function GetQuickLaunchBarVisibility() {
  return window['go']['main']['App']['GetQuickLaunchBarVisibility']();
}

export function GetQuickLaunchFavorites() {
  return window['go']['main']['App']['GetQuickLaunchFavorites']();
}

export function GetSSHHostDisplayNames() {
  return window['go']['main']['App']['GetSSHHostDisplayNames']();
}

export function GetSSHHostStatus() {
  return window['go']['main']['App']['GetSSHHostStatus']();
}

export function GetSSHHosts() {
  return window['go']['main']['App']['GetSSHHosts']();
}

export function GetSavedLayoutByID(arg1) {
  return window['go']['main']['App']['GetSavedLayoutByID'](arg1);
}

export function GetSavedLayouts() {
  return window['go']['main']['App']['GetSavedLayouts']();
}

export function GetScanMaxDepth() {
  return window['go']['main']['App']['GetScanMaxDepth']();
}

export function GetScanPaths() {
  return window['go']['main']['App']['GetScanPaths']();
}

export function GetScrollSpeed() {
  return window['go']['main']['App']['GetScrollSpeed']();
}

export function GetScrollback(arg1) {
  return window['go']['main']['App']['GetScrollback'](arg1);
}

export function GetScrollbackSize() {
  return window['go']['main']['App']['GetScrollbackSize']();
}

export function GetSessionMetadata(arg1) {
  return window['go']['main']['App']['GetSessionMetadata'](arg1);
}

export function GetSetupDismissed() {
  return window['go']['main']['App']['GetSetupDismissed']();
}

export function GetShowActivityRibbon() {
  return window['go']['main']['App']['GetShowActivityRibbon']();
}

export function GetSoftNewlineMode() {
  return window['go']['main']['App']['GetSoftNewlineMode']();
}

export function GetTerminalSettings() {
  return window['go']['main']['App']['GetTerminalSettings']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWindowNumber() {
  return window['go']['main']['App']['GetWindowNumber']();
}

export function HandleFileDrop(arg1, arg2, arg3) {
  return window['go']['main']['App']['HandleFileDrop'](arg1, arg2, arg3);
}

export function HandleRemoteImagePaste(arg1, arg2) {
  return window['go']['main']['App']['HandleRemoteImagePaste'](arg1, arg2);
}

export function HasScanPaths() {
  return window['go']['main']['App']['HasScanPaths']();
}

export function IsGitWorktree(arg1) {
  return window['go']['main']['App']['IsGitWorktree'](arg1);
}

export function IsPrimaryWindow() {
  return window['go']['main']['App']['IsPrimaryWindow']();
}

export function ListSSHHosts() {
  return window['go']['main']['App']['ListSSHHosts']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function ListSessionsWithGroups() {
  return window['go']['main']['App']['ListSessionsWithGroups']();
}

export function LogFrontendDiagnostic(arg1) {
  return window['go']['main']['App']['LogFrontendDiagnostic'](arg1);
}

export function MarkSessionAccessed(arg1) {
  return window['go']['main']['App']['MarkSessionAccessed'](arg1);
}

export function OpenNewWindow() {
  return window['go']['main']['App']['OpenNewWindow']();
}

export function RecordProjectUsage(arg1) {
  return window['go']['main']['App']['RecordProjectUsage'](arg1);
}

export function RefreshScrollback(arg1) {
  return window['go']['main']['App']['RefreshScrollback'](arg1);
}

export function RefreshSessionStatuses(arg1) {
  return window['go']['main']['App']['RefreshSessionStatuses'](arg1);
}

export function RefreshTerminalAfterResize(arg1) {
  return window['go']['main']['App']['RefreshTerminalAfterResize'](arg1);
}

export function RemoveQuickLaunchFavorite(arg1) {
  return window['go']['main']['App']['RemoveQuickLaunchFavorite'](arg1);
}

export function RemoveSSHHost(arg1) {
  return window['go']['main']['App']['RemoveSSHHost'](arg1);
}

export function RemoveScanPath(arg1) {
  return window['go']['main']['App']['RemoveScanPath'](arg1);
}

export function ResetGroupSettings() {
  return window['go']['main']['App']['ResetGroupSettings']();
}

export function ResetPipelineStats(arg1) {
  return window['go']['main']['App']['ResetPipelineStats'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveLaunchConfig(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['SaveLaunchConfig'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function SaveLayout(arg1) {
  return window['go']['main']['App']['SaveLayout'](arg1);
}

export function SaveOpenTabState(arg1) {
  return window['go']['main']['App']['SaveOpenTabState'](arg1);
}

export function SessionExists(arg1) {
  return window['go']['main']['App']['SessionExists'](arg1);
}

export function SetAllGroupsExpanded(arg1, arg2) {
  return window['go']['main']['App']['SetAllGroupsExpanded'](arg1, arg2);
}

export function SetAutoCopyOnSelectEnabled(arg1) {
  return window['go']['main']['App']['SetAutoCopyOnSelectEnabled'](arg1);
}

export function SetClickToCursorEnabled(arg1) {
  return window['go']['main']['App']['SetClickToCursorEnabled'](arg1);
}

export function SetDesktopTheme(arg1) {
  return window['go']['main']['App']['SetDesktopTheme'](arg1);
}

export function SetFileBasedActivityDetection(arg1) {
  return window['go']['main']['App']['SetFileBasedActivityDetection'](arg1);
}

export function SetFontSize(arg1) {
  return window['go']['main']['App']['SetFontSize'](arg1);
}

export function SetQuickLaunchBarVisibility(arg1) {
  return window['go']['main']['App']['SetQuickLaunchBarVisibility'](arg1);
}

export function SetScanMaxDepth(arg1) {
  return window['go']['main']['App']['SetScanMaxDepth'](arg1);
}

export function SetScanPaths(arg1) {
  return window['go']['main']['App']['SetScanPaths'](arg1);
}

export function SetScrollSpeed(arg1) {
  return window['go']['main']['App']['SetScrollSpeed'](arg1);
}

export function SetScrollbackSize(arg1) {
  return window['go']['main']['App']['SetScrollbackSize'](arg1);
}

export function SetSetupDismissed(arg1) {
  return window['go']['main']['App']['SetSetupDismissed'](arg1);
}

export function SetShowActivityRibbon(arg1) {
  return window['go']['main']['App']['SetShowActivityRibbon'](arg1);
}

export function SetSoftNewlineMode(arg1) {
  return window['go']['main']['App']['SetSoftNewlineMode'](arg1);
}

export function StartRemoteTmuxSession(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['StartRemoteTmuxSession'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function StartTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2, arg3);
}

export function StartTmuxSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartTmuxSession'](arg1, arg2, arg3, arg4);
}

export function TestSSHConnection(arg1) {
  return window['go']['main']['App']['TestSSHConnection'](arg1);
}

export function ToggleGroupExpanded(arg1, arg2) {
  return window['go']['main']['App']['ToggleGroupExpanded'](arg1, arg2);
}

export function UpdateQuickLaunchFavoriteName(arg1, arg2) {
  return window['go']['main']['App']['UpdateQuickLaunchFavoriteName'](arg1, arg2);
}

export function UpdateQuickLaunchShortcut(arg1, arg2) {
  return window['go']['main']['App']['UpdateQuickLaunchShortcut'](arg1, arg2);
}

export function UpdateSSHHost(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['UpdateSSHHost'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function UpdateSessionCustomLabel(arg1, arg2) {
  return window['go']['main']['App']['UpdateSessionCustomLabel'](arg1, arg2);
}

export function UpdateSessionStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateSessionStatus'](arg1, arg2);
}

export function ValidateMCPConfigPath(arg1) {
  return window['go']['main']['App']['ValidateMCPConfigPath'](arg1);
}

export function ValidateSSHHost(arg1, arg2) {
  return window['go']['main']['App']['ValidateSSHHost'](arg1, arg2);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
