#!/bin/bash
# Safe PR creation for agent-deck fork
# ALWAYS targets myrison/agent-deck, NEVER upstream

set -e

FORK_REPO="myrison/agent-deck"
BASE_BRANCH="main"
UPSTREAM_REPO="asheshgoplani/agent-deck"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

error() {
    echo -e "${RED}ERROR: $1${NC}" >&2
    exit 1
}

info() {
    echo -e "${GREEN}$1${NC}"
}

warn() {
    echo -e "${YELLOW}WARNING: $1${NC}"
}

# 1. Validate we're in a git repo
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    error "Not in a git repository"
fi

# 2. Get repository root and check if this is agent-deck
REPO_ROOT=$(git rev-parse --show-toplevel)
REPO_NAME=$(basename "$REPO_ROOT")

if [[ "$REPO_NAME" != "agent-deck" ]] && [[ "$REPO_ROOT" != *"agent-deck"* ]]; then
    error "This skill is only for the agent-deck repository. Current repo: $REPO_NAME"
fi

# 3. Validate gh CLI is installed
if ! command -v gh &> /dev/null; then
    error "gh CLI is not installed. Install: https://cli.github.com/"
fi

# 4. Get current branch
CURRENT_BRANCH=$(git branch --show-current)

if [[ "$CURRENT_BRANCH" == "main" ]]; then
    error "Cannot create PR from main branch. Create a feature branch first."
fi

# 5. Check if there are commits ahead of origin/main
git fetch origin main --quiet 2>/dev/null || true
COMMITS_AHEAD=$(git rev-list --count origin/main..HEAD 2>/dev/null || echo "0")

if [[ "$COMMITS_AHEAD" == "0" ]]; then
    error "No commits to PR. Current branch is up to date with origin/main."
fi

# 6. Extract PR title from arguments or prompt
PR_TITLE="$1"

if [[ -z "$PR_TITLE" ]]; then
    # Interactive mode - get most recent commit message as default
    DEFAULT_TITLE=$(git log -1 --pretty=%s)
    echo "Enter PR title (default: $DEFAULT_TITLE):"
    read -r INPUT_TITLE
    PR_TITLE="${INPUT_TITLE:-$DEFAULT_TITLE}"
fi

# 7. Generate PR body from commit messages
PR_BODY=$(cat <<EOF
## Changes

$(git log origin/main..HEAD --pretty=format:"- %s" --reverse)

## Files Changed

\`\`\`
$(git diff origin/main..HEAD --stat)
\`\`\`

---
Generated by /create-fork-pr skill
EOF
)

# 8. Show preview
info "========================================="
info "PR Preview"
info "========================================="
echo "Repository: $FORK_REPO"
echo "Base:       $BASE_BRANCH"
echo "Head:       $CURRENT_BRANCH"
echo "Title:      $PR_TITLE"
echo ""
echo "Body:"
echo "$PR_BODY"
info "========================================="

# 9. Confirm before creating
echo ""
warn "⚠️  IMPORTANT SAFETY CHECK ⚠️"
echo "Target repository: $FORK_REPO (the FORK)"
echo "NOT targeting:     $UPSTREAM_REPO (upstream)"
echo ""
echo "Proceed with PR creation? (y/N)"
read -r CONFIRM

if [[ "$CONFIRM" != "y" ]] && [[ "$CONFIRM" != "Y" ]]; then
    echo "Cancelled."
    exit 0
fi

# 10. Push current branch if not already pushed
if ! git ls-remote --exit-code origin "$CURRENT_BRANCH" &>/dev/null; then
    info "Pushing $CURRENT_BRANCH to origin..."
    git push -u origin "$CURRENT_BRANCH"
fi

# 11. Create PR with EXPLICIT repo targeting
info "Creating PR on $FORK_REPO..."

PR_URL=$(gh pr create \
    --repo "$FORK_REPO" \
    --base "$BASE_BRANCH" \
    --head "$CURRENT_BRANCH" \
    --title "$PR_TITLE" \
    --body "$PR_BODY")

info "========================================="
info "✅ PR Created Successfully!"
info "========================================="
echo "URL: $PR_URL"
echo ""
info "Target: $FORK_REPO (fork - CORRECT)"
info "Base:   $BASE_BRANCH"
